#!/bin/bash

protected_branch='refs/heads/main'

while read local_ref local_sha remote_ref remote_sha
do
    if [[ $protected_branch = $remote_ref ]]
    then
        echo "  ... $local_sha"
        echo "Blocking the push to main from pre-push script"
        exit 1
    fi
done

exit 0